# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jsmestad-chargify}
  s.version = '0.3.3'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.authors = ['Wynn Netherland', 'Justin Smestad']
  s.date = %q{2010-10-02}
  s.email = %q{justin.smestad@gmail.com}
  s.extra_rdoc_files = %w(LICENSE README.markdown)
  s.files = `git ls-files`.split("\n")

  s.homepage = %q{http://github.com/jsmestad/chargify}
  s.rdoc_options = %w(--charset=UTF-8)
  s.require_paths = %w(lib)
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby wrapper for the Chargify API}
  s.test_files = Dir.glob('spec/**/*.rb')

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ['>= 0.7.6'])
      s.add_runtime_dependency(%q<hashie>, ['>= 0.1.8'])
      s.add_runtime_dependency(%q<oj>, ['~> 2.0'])
      s.add_runtime_dependency(%q<activesupport>, ['>= 3.0.0'])
    else
      s.add_dependency(%q<httparty>, ['>= 0.7.6'])
      s.add_dependency(%q<hashie>, ['>= 0.1.8'])
      s.add_dependency(%q<oj>, ['~> 2.0'])
      s.add_dependency(%q<activesupport>, ['>= 3.0.0'])
    end
  else
    s.add_dependency(%q<httparty>, ['>= 0.7.6'])
    s.add_dependency(%q<hashie>, ['>= 0.1.8'])
    s.add_dependency(%q<oj>, ['~> 2.0'])
    s.add_dependency(%q<activesupport>, ['>= 3.0.0'])
  end
end

